// components/WhyItMatters.tsx
import Link from 'next/link';

export default function WhyItMatters() {
    return (
        <section className="py-24 px-6 bg-[#0f1013]">
            <div className="max-w-6xl mx-auto">

                {/* Heading */}
                <div className="text-center max-w-3xl mx-auto">
                    <h2 className="text-3xl md:text-4xl font-bold text-[#f2f3f5]">
                        Why It Matters for Hardware Buyers
                    </h2>

                    <p className="mt-4 text-[#b0b4bb] text-lg">
                        Choosing hardware for AI is confusing.
                        Marketing specs don’t reflect real performance —
                        this benchmark shows what actually matters.
                    </p>
                </div>

                {/* Content Grid */}
                <div className="mt-16 grid gap-10 md:grid-cols-3">

                    {/* Card 1 */}
                    <div className="rounded-xl bg-[#18191c] p-6 border border-[#34363c]">
                        <h3 className="text-lg font-semibold text-[#f2f3f5]">
                            Real AI Performance, Not Specs
                        </h3>
                        <p className="mt-3 text-sm text-[#b0b4bb] leading-relaxed">
                            Clock speeds, core counts, and “AI TOPS” don’t tell
                            you how fast models actually run.
                            These benchmarks measure real AI inference on
                            real consumer hardware.
                        </p>
                    </div>

                    {/* Card 2 */}
                    <div className="rounded-xl bg-[#18191c] p-6 border border-[#34363c]">
                        <h3 className="text-lg font-semibold text-[#f2f3f5]">
                            Compare Before You Buy
                        </h3>
                        <p className="mt-3 text-sm text-[#b0b4bb] leading-relaxed">
                            See how laptops, desktops, GPUs, and integrated
                            graphics perform across the same workloads.
                            No vendor bias, no synthetic-only rankings.
                        </p>
                    </div>

                    {/* Card 3 */}
                    <div className="rounded-xl bg-[#18191c] p-6 border border-[#34363c]">
                        <h3 className="text-lg font-semibold text-[#f2f3f5]">
                            Avoid Overpaying
                        </h3>
                        <p className="mt-3 text-sm text-[#b0b4bb] leading-relaxed">
                            Many systems cost more without delivering better
                            AI performance.
                            Real benchmarks help identify the best
                            performance per price options.
                        </p>
                    </div>

                    {/* Card 4 */}
                    <div className="rounded-xl bg-[#18191c] p-6 border border-[#34363c]">
                        <h3 className="text-lg font-semibold text-[#f2f3f5]">
                            Know What Runs Locally
                        </h3>
                        <p className="mt-3 text-sm text-[#b0b4bb] leading-relaxed">
                            Not all devices can run AI models smoothly.
                            Benchmarks reveal which hardware can load,
                            run, and sustain local AI workloads reliably.
                        </p>
                    </div>

                    {/* Card 5 */}
                    <div className="rounded-xl bg-[#18191c] p-6 border border-[#34363c]">
                        <h3 className="text-lg font-semibold text-[#f2f3f5]">
                            Future-Proof Your Purchase
                        </h3>
                        <p className="mt-3 text-sm text-[#b0b4bb] leading-relaxed">
                            As local AI adoption grows, knowing real
                            performance today helps you choose hardware
                            that stays relevant longer.
                        </p>
                    </div>

                    {/* Card 6 */}
                    <div className="rounded-xl bg-[#18191c] p-6 border border-[#34363c]">
                        <h3 className="text-lg font-semibold text-[#f2f3f5]">
                            Community-Verified Results
                        </h3>
                        <p className="mt-3 text-sm text-[#b0b4bb] leading-relaxed">
                            Results are generated by real users on real devices.
                            The more people benchmark, the clearer the
                            picture becomes for future buyers.
                        </p>
                    </div>

                </div>

                {/* CTA */}
                <div className="mt-20 text-center">
                    <Link
                        href="/benchmark"
                        className="inline-flex items-center gap-2 px-8 py-3
                            rounded-lg border border-[#4fbf8a]
                            text-[#f2f3f5] font-medium
                            bg-[#4fbf8a]/10
                            hover:bg-[#4fbf8a]/20 transition"
                    >
                        Check Your Hardware →
                    </Link>
                </div>

            </div>
        </section>
    );
}
